// Write a function called fizzbuzz which takes a number as its input. It should return the number that is passed to it, unless the number is:

// divisible by 15, then it should be replaced with the string "FizzBuzz"
// divisible by 5, then it should be replaced with the string "Buzz"
// divisible by 3, then it should be replaced with the string "Fizz"

function fizzbuzz(numberParameter) {
  //work out if a number is whole when divided by another number
  function isWholeNumber(dividedBy) {
    // calculate numberParameter divided by a number
    const result = numberParameter / dividedBy
    //is the result a whole number?
    if (result % 1 === 0) {
      return true
    } else {
      return false
    }
  }
  //divisible by 15 is same as divisible by 3 and 5 - check if both are true
  if (isWholeNumber(3) & isWholeNumber(5)) {
    //console.log(`FizzBuzz - ${numberParameter} is divisible by both 5 and 3`)
    return 'FizzBuzz'
    //check if divisible by only 5
  } else if (isWholeNumber(5)) {
    //console.log(`Buzz - ${numberParameter} is divisible by 5 only`)
    return 'Buzz'
    //check if divisible by only 3
  } else if (isWholeNumber(3)) {
    //console.log(`Fizz - ${numberParameter} is divisible by 3 only`)
    return 'Fizz'
    //return number if none of the above are true
  } else {
    //console.log(`${numberParameter} is not divisible by 3 or 5`)
    return numberParameter
  }
}

const randomNumber = Math.floor(Math.random() * 1000)
// console.log(
//   `${randomNumber} - This number has been generated by the function randomNumber in fizzbuzz.js`
// )

fizzbuzz(randomNumber)

// write your code above this line----------------------------------
// -----------------------------------------------------------------
module.exports = { fizzbuzz }
